"""add password model

Revision ID: 011792b90e52
Revises: e477307b98f3
Create Date: 2024-04-16 12:34:03.115325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011792b90e52'
down_revision = 'e477307b98f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_password_user_id", 'user', ['user_id'], ['id'])
        batch_op.create_check_constraint("chk_password_strength", condition="LENGTH(password) BETWEEN 8 AND 20")
        # Добавьте другие ограничения, если необходимо

    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
