"""start123

Revision ID: ae06dba164e2
Revises: 86461a098a5f
Create Date: 2024-04-18 23:41:05.558483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae06dba164e2'
down_revision = '86461a098a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
